name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'mkaraki/ServiceFaultInformationGenerator'
        path: 'app'
        
    - uses: actions/checkout@v3
      with:
        path: 'site'
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      run: |
        cd site
        dotnet run --project "../app/ServiceFaultInformationGenerator/ServiceFaultInformationGenerator.csproj" -- build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/out
        cname: status.mkarakiapps.com
